#pragma once

#include <proton/MiscUtils.h>
#include "TileExtra.h"

#define TILEFLAG_EXTRA (1 << 0)

enum eTileExtraType
{
	TILE_EXTRA_NONE,
	TILE_EXTRA_DOOR,
	TILE_EXTRA_SIGN,
	TILE_EXTRA_LOCK,
	TILE_EXTRA_TREE,
	TILE_EXTRA_UNK_5,
	TILE_EXTRA_MAILBOX,
	TILE_EXTRA_BULLETIN,
	TILE_EXTRA_DICE,
	TILE_EXTRA_PROVIDER,
	TILE_EXTRA_ACHIEVEMENT_BLOCK,
	TILE_EXTRA_HEART_MONITOR,
	TILE_EXTRA_DONATION_BOX,
	TILE_EXTRA_TOY_BOX,
	TILE_EXTRA_MANNEQUIN,
	TILE_EXTRA_MAGIC_EGG,
	TILE_EXTRA_GAME_BLOCK,
	TILE_EXTRA_GAME_GENERATOR,
	TILE_EXTRA_XENONITE,
	TILE_EXTRA_DRESSUP,
	TILE_EXTRA_CRYSTAL,
	TILE_EXTRA_BURGLAR,
	TILE_EXTRA_SPOTLIGHT,
	TILE_EXTRA_DISPLAY_BLOCK,
	TILE_EXTRA_VENDING_MACHINE,
	TILE_EXTRA_FISHTANK,
	TILE_EXTRA_SOLAR,
	TILE_EXTRA_FORGE,
	TILE_EXTRA_GIVING_TREE,
	TILE_EXTRA_GIVING_TREE_STUMP,
	TILE_EXTRA_STEAM_ORGAN,
	TILE_EXTRA_SILKWORM,
	TILE_EXTRA_SEWING_MACHINE,
	TILE_EXTRA_FLAG,
	TILE_EXTRA_LOBSTER_TRAP,
	TILE_EXTRA_ART_CANVAS,
	TILE_EXTRA_BATTLE_CAGE,
	TILE_EXTRA_PET_TRAINER,
	TILE_EXTRA_STEAM_ENGINE,
	TILE_EXTRA_LOCK_BOT,
	TILE_EXTRA_BACKGROUND_WEATHER,
	TILE_EXTRA_SPIRIT_STORAGE,
	TILE_EXTRA_DATA_BEDROCK,
	TILE_EXTRA_DISPLAY_SHELF,
	TILE_EXTRA_VIP_TIMER,
	TILE_EXTRA_CHALLENGE_TIMER,
	TILE_EXTRA_UNK_46,
	TILE_EXTRA_FISH_MOUNT,
	TILE_EXTRA_PORTRAIT,
	TILE_EXTRA_STUFF_WEATHER,
	TILE_EXTRA_FOSSIL_PREP,
	TILE_EXTRA_DNA_MACHINE,
	TILE_EXTRA_TRICKSTER,
	TILE_EXTRA_CHEMTANK,
	TILE_EXTRA_STORAGE,
	TILE_EXTRA_OVEN,
	TILE_EXTRA_SUPER_MUSIC,
	TILE_EXTRA_GEIGER_CHARGER,
	TILE_EXTRA_ADVENTURE_RESET,
	TILE_EXTRA_TOMB_ROBBER,
	TILE_EXTRA_FACTION,
	TILE_EXTRA_TRAINING_FISH_PORT,
	TILE_EXTRA_ITEM_SUCKER,
	TILE_EXTRA_ROBOT,
	TILE_EXTRA_TICKET,
	TILE_EXTRA_GUILD_ITEM,
	TILE_EXTRA_STATS_BLOCK,
	TILE_EXTRA_FIELD_NODE,
	TILE_EXTRA_OUIJA_BOARD,
	TILE_EXTRA_AUTO_BREAK,
	TILE_EXTRA_AUTO_HARVEST,
	TILE_EXTRA_AUTO_HARVEST_SUCKER,
	TILE_EXTRA_LIGHTNING_IF_ON,
	TILE_EXTRA_PHASED_BLOCK,
	TILE_EXTRA_SAFE_VAULT,
	TILE_EXTRA_PHASED_BLOCK2,
	TILE_EXTRA_PVE_NPC,
	TILE_EXTRA_INFINITY_WEATHER,
	TILE_EXTRA_COMPLETIONIST,
	TILE_EXTRA_FEEDING_BLOCK,
	TILE_EXTRA_KRANKENS_BLOCK,
	TILE_EXTRA_FRIENDS_ENTRANCE
};

class Tile
{
public:
    void Serialize(uint8_t* pData, int& offset, bool bWriteToMem, bool bClientPacket = true);
    void SerializeExtra(uint8_t* pData, int& offset, bool bWriteToMem, bool bClientPacket = true);
    uint32_t GetEstimatedMem(bool bClientPacket = true);

    void SetFG(short fg, bool bSetTileExtra = false);
    TileExtra* GetExtraDataDefault(ItemInfo* pItem);

    short m_fg{};
    short m_bg{};
    short m_flags{};
    short m_parent{};
    TileExtra* m_pExtra = nullptr;

    // extra members not needed in serialization
    int m_index{};
};